version: "3.9"
services:
  postgres:
    container_name: db
    image: "postgres:17.5"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/:ro # turn it on, if you need run init DB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - local
    ports:
      - "5432:5432"

  # pgadmin:
  #   container_name: pgadmin
  #   image: "dpage/pgadmin4:5.1"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres@domain.local
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - local

  keycloak:
    container_name: keycloak
    build:
      context: .
      args:
        KEYCLOAK_VERSION: 26.2.0
    command: ["start", "--optimized"]
    environment:
      JAVA_OPTS_APPEND: >-
        -Dkeycloak.profile.feature.upload_scripts=enabled
        -Dkeycloak.hostname.fixed.hostname-strict=false
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      # KC_HOSTNAME: keycloak.localhost
      # KC_HOSTNAME_PORT: 8180
      # KC_HOSTNAME_URL: http://keycloak.localhost:8180
      KC_HOSTNAME_URL: https://thanhndbkeycloak.shop
      KC_PROXY: reencrypt
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge