receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318


processors:
  batch:

exporters: 
  otlphttp/loki:
    endpoint: http://loki-svc:3100/otlp
    tls:
      insecure: true
  debug:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki, debug]